// Single source of truth for region scores.
//
// Prefers live scores generated by the Bright Data pipeline
// (data/scores.generated.json, written by `npm run scores`). Falls back to the
// built-in MOCK_SCORES whenever the live file is empty — so the app works
// identically before the Bright Data account is connected.

import { MOCK_SCORES, RankedOpportunity } from "@/lib/types";
import generated from "@/data/scores.generated.json";

const LIVE = generated as unknown as RankedOpportunity[];

export const IS_LIVE = Array.isArray(LIVE) && LIVE.length > 0;

export const ALL_SCORES: RankedOpportunity[] = IS_LIVE ? LIVE : MOCK_SCORES;

/** Scores for one corridor (by ISO), ranked. */
export function scoresFor(iso: string): RankedOpportunity[] {
  return ALL_SCORES
    .filter(s => s.target_country_iso === iso)
    .sort((a, b) => a.rank - b.rank);
}
